DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS library_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS library;
DROP TABLE IF EXISTS downloads;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS settings;
